    IF !DEF(IMAGES_INC)
DEF IMAGES_INC = 1

    EXPORT splashscreen_map_data
    EXPORT splashscreen_map_data_end
    EXPORT splashscreen_tile_data
    EXPORT splashscreen_tile_data_end
    EXPORT credits_map_data
    EXPORT credits_map_data_end
    EXPORT menu_map_data
    EXPORT menu_map_data_end
    EXPORT gamewindow_map_data
    EXPORT gamewindow_map_data_end
    EXPORT gamewindow_tile_data
    EXPORT gamewindow_tile_data_end
    EXPORT studiologo_map_data
    EXPORT studiologo_map_data_end
    EXPORT studiologo_tile_data
    EXPORT studiologo_tile_data_end

    ENDC ; IMAGES_INC