    IF !DEF(IMAGES_INC)
DEF IMAGES_INC = 1

    EXPORT pipecorner0_tile_data
    EXPORT pipecorner0_tile_data_end
    EXPORT pipecorner1_tile_data
    EXPORT pipecorner1_tile_data_end
    EXPORT pipecorner2_tile_data
    EXPORT pipecorner2_tile_data_end
    EXPORT pipecorner3_tile_data
    EXPORT pipecorner3_tile_data_end
    EXPORT pipecross0_tile_data
    EXPORT pipecross0_tile_data_end
    EXPORT pipestraight0_tile_data
    EXPORT pipestraight0_tile_data_end
    EXPORT pipestraight1_tile_data
    EXPORT pipestraight1_tile_data_end
    EXPORT pipet0_tile_data
    EXPORT pipet0_tile_data_end
    EXPORT pipet1_tile_data
    EXPORT pipet1_tile_data_end
    EXPORT pipet2_tile_data
    EXPORT pipet2_tile_data_end
    EXPORT pipet3_tile_data
    EXPORT pipet3_tile_data_end

    ENDC ; IMAGES_INC